# Generated by Django 5.2.4 on 2025-07-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('codeforces', 'Codeforces'), ('atcoder', 'AtCoder'), ('codechef', 'CodeChef'), ('leetcode', 'LeetCode')], max_length=32)),
                ('contest_id', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('url', models.URLField()),
            ],
            options={
                'unique_together': {('platform', 'contest_id')},
            },
        ),
    ]
